server:
  port: 8080
  servlet:
    session:
      timeout: 4h

spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB


logging:
  level:
   com.tongu.search: DEBUG
   org.springframework: INFO

