server:
  port: 8080
  servlet:
    session:
      timeout: 4h

spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  datasource:
    druid:
      football:
        url: jdbc:postgresql://postgresql-standby.uecent.com:5432/udata
        username: developer_readonly
        password: VhTo2E6QpUWvdF51
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      basketball:
        url: jdbc:postgresql://postgresql-standby.uecent.com:5432/udata-basketball
        username: developer_readonly
        password: VhTo2E6QpUWvdF51
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      locale:
        #url: jdbc:postgresql://postgresql-locale.uecent.com:5432/udata-locale
        url: jdbc:postgresql://35.247.170.107:7002/udata-locale
        username: developer
        password: ZDyz8u2OFIYH50bT
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


logging:
  level:
   com.tongu.search: DEBUG
   org.springframework: INFO

